# Generated by Django 5.1.6 on 2025-06-05 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api2d", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Api2dGroup2ExpirationMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("group", models.CharField(max_length=100)),
                ("validate_days", models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name="api2dkey",
            name="group",
            field=models.CharField(default="dev-0", max_length=100),
            preserve_default=False,
        ),
    ]
