# Generated by Django 5.1.6 on 2025-06-05 07:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api2d", "0002_api2dgroup2expirationmapping_api2dkey_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="Api2dGroup2ExpirationMapping",
            name="type_id",
            field=models.CharField(default="0", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="api2dkey",
            name="expired_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="Api2dGroup2ExpirationMapping",
            name="group",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="api2dkey",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="api_keys",
                to="api2d.Api2dGroup2ExpirationMapping",
            ),
        ),
    ]
