# Generated by Django 5.1.6 on 2025-06-08 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api2d", "0003_api2dgroup2expirationmapping_type_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="api2dkey",
            name="expired_at",
            field=models.DateTimeField(null=True),
        ),
    ]
