# Generated by Django 5.1.6 on 2025-06-10 08:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api2d", "0004_alter_api2dkey_expired_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="api2dkey",
            options={"verbose_name": "API Key", "verbose_name_plural": "API Keys"},
        ),
        migrations.AlterField(
            model_name="api2dkey",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
