repos:
-   repo: local
    hooks:
    -   id: git-secrets
        name: git-secrets
        description: Prevents committing sensitive information
        entry: git secrets --pre_commit_hook --no-index
        language: system
        types: [text]
        stages: [commit, push]
        verbose: true
        always_run: true

-   repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
    - id: black
      language_version: python3.10
      types_or: [python, pyi]