version: '3.8'

services:
  web:
    build:
      context: .
      target: production
      args:
        - ENV=production
    command: >
      sh -c "python manage.py migrate &&
             gunicorn django_project.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    expose:
      - 8000
    env_file:
      - .env.prod
    depends_on:
      - db
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G

  db:
    image: postgres:15
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST_AUTH_METHOD=trust
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G


volumes:
  postgres_data_prod:
  static_volume:
  media_volume:
