# Generated by Django 5.1.6 on 2025-06-08 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "slug",
                    models.SlugField(
                        help_text='Used in the URL (e.g., "about-us" for /about-us/)',
                        max_length=200,
                        unique=True,
                    ),
                ),
                (
                    "content",
                    models.TextField(help_text="Markdown content for the page"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Page",
                "verbose_name_plural": "Pages",
                "ordering": ["title"],
                "indexes": [models.Index(fields=["slug"], name="pages_page_slug_idx")],
            },
        ),
    ]
